[package]
name = "artm"
version = "0.2.0"
authors = ["Anthony Wilcox"]
license = "GNU GPL v3"
edition = "2018"
description = """
A request, commmission, and YCH art manager.
"""

[dependencies]
serde_json = "1.0"

[dependencies.uuid]
version = "0.7"
features = ["serde", "v4"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.clap]
version = "2.32"
features = [ "yaml", "wrap_help" ]