name: Rust

on:
  push:
    branches: [master, develop]
    pull_request: [master, develop]
    schedule:
      - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose